spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls-enable: true
        starttls-required: true
        connection-timeout: 5000
        timeout: 5000
        write-timeout: 5000

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  swagger-ui:
    path: /api-docs

coolsms:
  api:
    key: ${COOL_SMS_KEY}
    secret: ${COOL_SMS_SECRET}
    from: ${COOL_FROM}

cloud:
  aws:
    credentials:
      access-key: ${CREDENTIALAS_ACCESS_KEY}
      secret-key: ${CREDENTIALAS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
      
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

fcm:
  private:
    key:
      path: ${FCM_KEY_PATH}
      scope: ${FCM_SCOPE}
