spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      smtp:
        auth: true
        starttls-enable: true
        starttls-required: true
        connection-timeout: 5000
        timeout: 5000
        write-timeout: 5000

springdoc:
  swagger-ui:
    path: /api-docs

coolsms:
  api:
    key: key
    secret: secret
    from: from

cloud:
  aws:
    credentials:
      access-key: accesskey
      secret-key: secretkey
    s3:
      bucket: bucketname
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  issuer: issuer

fcm:
  private:
    key:
      path: firebase/private-key.json
      scope: scope
