package com.example.sabujak.post.entity;

import lombok.Getter;

@Getter
public enum Category {
    OWNER, OFFICE, FINANCE, HRD, PROMOTION, ITDEV, ITPLAN, SALE, DESIGN, SERVICE,
    CONTENTS, RND, PROFESSIONAL, MD, INSURANCE, ETC, ALL, FREE_BOARD, COMPANY_LIFE,
    INVESTMENT_FINANCE, STUDY_PROMOTION, EXERCISE, FOOD, CULTURAL_LIFE, FAMILY_PET
}
